### PR TITLE
Enhacement/update docs

### PR DESCRIPTION
**Pull request by pgarciaegido**

### CODE REVIEW

**Comment by mPaella** [comment]
We probably should forward people to the docs website, instead of having to maintain this? 

https://docs.crossmint.io/

**Comment by pgarciaegido** [comment]
I think that makes sense, altough is true that its nice when you enter in a repo and you have a good readme that get you on track super fast. Maybe we could simplify it so we have the very basic installation and setup process and then the link to the docs.

**Review by alfonso-paella — APPROVED** [review]
Sounds fine but as Maxwell was suggesting, I would put a very visibile link to docs.crossmint.io somewhere

**Comment by pgarciaegido** [comment]
Added a link to docs.crossmint.io on top of the 3 readme.

**Review by alfonso-paella — APPROVED** [review]

**Pull request merged**
